In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier as knn
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.tree  import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier

In [ ]:
taxo=pd.read_excel('C:/Users/Administrator/Downloads/Taxonomy_Dataset.xlsx')

In [ ]:
taxo.head(3)

In [ ]:
taxo['Normalized_Category'].unique()

In [ ]:
taxo['merchant_category_Level3'].unique()

In [ ]:
taxo.shape

In [ ]:
taxo.isnull().sum()

In [ ]:
taxo=taxo.fillna(method='bfill')

In [ ]:
taxo.isnull().sum()

In [ ]:
taxo.dtypes

In [ ]:
from sklearn.preprocessing import LabelEncoder
x1=LabelEncoder()
#taxo['Gender']=x1.fit_transform(taxo['Gender'])
taxo['Normalized_Category']=x1.fit_transform(taxo['Normalized_Category'])
taxo['Gender']=x1.fit_transform(taxo['Gender'])
taxo['merchant_category_Level 1']=x1.fit_transform(taxo['merchant_category_Level 1'])
taxo['merchant_category_Level2']=x1.fit_transform(taxo['merchant_category_Level2'])
taxo['merchant_category_Level3']=x1.fit_transform(taxo['merchant_category_Level3'])
taxo['Brand']=x1.fit_transform(taxo['Brand'])
taxo['Pattern']=x1.fit_transform(taxo['Pattern'])
taxo['Material']=x1.fit_transform(taxo['Material'])
taxo['Occasion']=x1.fit_transform(taxo['Occasion'])
taxo['Color']=x1.fit_transform(taxo['Color'])
taxo['Title']=x1.fit_transform(taxo['Title'])
taxo['Description']=x1.fit_transform(taxo['Description'])


taxo.head(2)

In [ ]:
## predicting the normalizing category
y=taxo['Normalized_Category']
x=taxo.drop(['Normalized_Category','product_id'],axis=1)

In [ ]:
x.head()

In [ ]:
y.head()

In [ ]:
#x1=pd.get_dummies(x)
#x1.head()
#x1.shape

In [ ]:
#x1=x['price']
#x1=pd.DataFrame(x1)
#x1

In [ ]:
#sc = StandardScaler()
# Fitting the object on our data
#X_scaled = sc.fit_transform(x1)
#x_scaler=pd.DataFrame(X_scaled)


In [ ]:
#x=x.drop(['price'],axis=1)
#x2=pd.concat([x_scaler,x],axis=1)
#x2=x2.drop(['price'],axis=1)
#x2


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 123 )

In [ ]:
len(x_test)

In [ ]:
len(x_train)

In [ ]:
import statsmodels.formula.api as smf
model=smf.OLS(y_train,x_train).fit()
model.summary()

In [ ]:
gn=GaussianNB()
gn.fit(x_train,y_train)
predict=gn.predict(x_test)

In [294]:
print('Naive score=',gn.score(x_test,y_test)*100)

Naive score= 78.3876500857633


In [295]:
clfl=DecisionTreeClassifier()
clfl.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [296]:
Y_pred=clfl.predict(x_test)
Y_pred

array([61, 61, 43, 56, 36, 65, 43, 10, 65, 18, 36, 17, 47, 65, 36, 47, 19,
       47, 24, 27, 32, 46, 10, 47, 33, 32, 17, 47, 48, 32, 24, 24,  0, 10,
       62, 43, 33, 43, 47, 64, 65, 36, 33, 33, 36, 47, 65, 43, 64, 33, 33,
       61,  1, 47, 43, 65, 33, 43, 33, 25, 47,  3, 18, 33, 47, 66, 39, 47,
       33, 33, 17, 36, 23, 47, 47, 47, 47, 33, 47, 62, 47, 67, 61, 47, 47,
       32, 48, 66, 10, 62, 47, 43, 36, 43, 47, 47, 10, 47, 43, 36, 36, 33,
       47,  2, 10, 47, 61, 47, 43, 47, 33, 36, 22,  0,  6, 33, 47, 36, 67,
        2, 61, 46,  0, 43, 47, 48, 33, 61, 43, 28, 36, 47, 33, 54, 61, 10,
       10, 47, 47, 36,  2, 47,  8, 47, 33, 61, 47, 39, 43, 28, 62, 33, 36,
       33, 36,  8, 65, 47, 33, 32, 43, 17, 43, 66, 62, 32, 54, 47, 27, 36,
       47, 47, 33, 47, 33, 20,  3, 32, 32, 33, 36, 22, 26, 65, 47, 62, 47,
       33, 33, 67, 47, 66, 57, 56, 10, 32, 43, 22, 33,  0, 36, 47, 43, 47,
       66, 33, 47, 50, 20, 28, 69, 47, 47, 65, 43, 47,  2, 43, 47, 65, 47,
       61, 50, 20, 36, 62

In [297]:
print('accuracy=',accuracy_score(y_test,Y_pred))

accuracy= 0.8782161234991424


In [298]:
CM=confusion_matrix(y_test,Y_pred)
print('Confusion matrix is:',CM,sep='\n')

Confusion matrix is:
[[11  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ...  5  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [332]:
clf2=DecisionTreeClassifier(criterion='entropy',splitter='best',max_leaf_nodes=20,min_samples_leaf=12,max_depth=5)
clf2.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=20,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=12, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [333]:
Y1_predict=clf2.predict(x_test)

In [334]:
print('accuracy=',accuracy_score(y_test,Y1_predict))

accuracy= 0.8353344768439108


In [337]:
rf=RandomForestClassifier(n_estimators=100,random_state=0)
# n_estimators indicates the number of trees in the forest
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.9005145797598628

In [340]:
ab=AdaBoostClassifier(n_estimators=100)
ab.fit(x_train,y_train)
y_pred1=ab.predict(x_test)
accuracy_score(y_test,y_pred1)

0.1269296740994854

In [341]:
gb=GradientBoostingClassifier(n_estimators=100)
gb.fit(x_train,y_train)
y_pred=gb.predict(x_test)
accuracy_score(y_test,y_pred)

0.8902229845626072

In [345]:
xgb=XGBClassifier()
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)
accuracy_score(y_test,y_pred)

0.9159519725557461

## Maximum accuracy is achieved by xgboost